language: python
python:
  - "3.6"
services:
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'CREATE DATABASE StructureDB;' -U postgres
  - bash -c "psql -c 'CREATE USER structure_admin WITH PASSWORD \'${STRUCTURE_ADMIN_PASSWORD}\';' -U postgres"
  - python structure_server/manage.py migrate
script:
  - flake8 structure_server
