"""
Django settings for structure_server project.

Generated by 'django-admin startproject' using Django 2.1.
"""

import base64
import os

import dj_database_url


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


SECRET_KEY = """
Good practice for Django Applications suggest that secret keys should not be
defined as hard-coded strings in the settings.py file.
"""
SECRET_KEY = os.environ.get(
    "STRUCTURE_KEY", base64.b64encode(SECRET_KEY.encode()).decode()
)

DEBUG = True

ALLOWED_HOSTS = [
    'structure-server.herokuapp.com',
    '127.0.0.1'
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "dashboard",
]

AUTHENTICATION_BACKENDS = [
    "dashboard.auth.backends.AuthBackend"
]

AUTH_USER_MODEL = "dashboard.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "structure_server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]

WSGI_APPLICATION = "structure_server.wsgi.application"


# Database

DB_USER = os.environ.get("DB_USER") or "structure_admin"
PASSWORD = os.environ.get("STRUCTURE_ADMIN_PASSWORD")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "StructureDB",
        "USER": DB_USER,
        "PORT": "5432",
    }
}

if os.environ.get('DATABASE_URL') is not None:
    DATABASES["default"] = dj_database_url.config(
        conn_max_age=600, ssl_require=True
    )

if PASSWORD is not None:
    DATABASES["default"].update({"PASSWORD": PASSWORD})

# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        )
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation." "MinimumLengthValidator"
        )
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        )
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        )
    },
]

# Internationalization

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/London"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = '/static/'
