# Generated by Django 2.1 on 2018-09-07 15:02

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("auth", "0009_alter_user_last_name_max_length")]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Designates that this user has all "
                            "permissions without explicitly assigning them."
                        ),
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "user_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("username", models.CharField(max_length=8, unique=True)),
                ("password", models.CharField(max_length=20)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text=(
                            "The groups this user belongs to. A user will get"
                            " all permissions granted to each of their groups."
                        ),
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={"db_table": "user"},
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "class_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("teacher", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=50)),
                ("room", models.CharField(max_length=10)),
            ],
            options={"db_table": "class"},
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "form_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("form_group", models.CharField(max_length=10)),
                ("hall_head", models.CharField(max_length=50)),
                (
                    "class_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.Class",
                    ),
                ),
            ],
            options={"db_table": "form"},
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "student_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=29)),
                ("avatar", models.CharField(max_length=20000)),
                ("reference_number", models.CharField(max_length=12)),
                ("tutor", models.CharField(max_length=50)),
                (
                    "timetable",
                    django.contrib.postgres.fields.jsonb.JSONField(),
                ),
                (
                    "attendance",
                    django.contrib.postgres.fields.jsonb.JSONField(),
                ),
                ("markbook", django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={"db_table": "student"},
        ),
        migrations.AddField(
            model_name="user",
            name="student_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.Student",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.Permission",
                verbose_name="user permissions",
            ),
        ),
    ]
